-- Populate subject abbreviations and require abbrevation without default

UPDATE "Subject"
SET "abbrevation" = CASE id
  WHEN 1 THEN 'SLO'
  WHEN 2 THEN 'MAT'
  WHEN 3 THEN 'TJ'
  WHEN 4 THEN 'ŠV'
  WHEN 5 THEN 'DRU'
  WHEN 6 THEN 'NAR'
  WHEN 7 THEN 'UME'
  WHEN 8 THEN 'GRAD'
  WHEN 9 THEN 'OGT'
  WHEN 10 THEN 'SR'
  WHEN 11 THEN 'STAV'
  WHEN 12 THEN 'OP'
  WHEN 13 THEN 'GM'
  WHEN 14 THEN 'GIO'
  WHEN 15 THEN 'FIZ'
  WHEN 16 THEN 'KEM'
  WHEN 17 THEN 'INF'
  WHEN 18 THEN 'MIM'
  WHEN 19 THEN 'GRN'
  WHEN 20 THEN 'GE'
  WHEN 21 THEN 'ZIO'
  WHEN 22 THEN 'DIM'
  WHEN 23 THEN 'TES'
  WHEN 24 THEN 'SMG'
  WHEN 25 THEN 'PPK'
  WHEN 26 THEN 'SČ'
  WHEN 27 THEN 'ZID'
  WHEN 28 THEN 'TD'
  WHEN 29 THEN 'MVG'
  WHEN 30 THEN 'ZGO'
  WHEN 31 THEN 'VO'
  WHEN 32 THEN 'TRUR'
  WHEN 33 THEN 'MIO'
  WHEN 34 THEN 'OVT'
  WHEN 35 THEN 'BIO'
  WHEN 36 THEN 'GEO'
  WHEN 37 THEN 'SOC'
  WHEN 38 THEN 'ID'
  WHEN 39 THEN 'PVGD'
  WHEN 40 THEN 'NMV'
  WHEN 41 THEN 'KIP'
  WHEN 42 THEN 'GVG'
  WHEN 43 THEN '3D'
  WHEN 44 THEN 'SIVZ'
  WHEN 45 THEN 'URE'
  WHEN 46 THEN 'PS'
  WHEN 47 THEN 'PGIO'
  WHEN 48 THEN 'GEOP'
  WHEN 49 THEN 'IPD'
  WHEN 50 THEN 'ODP'
  WHEN 51 THEN 'OZ'
  WHEN 52 THEN 'GO'
  WHEN 53 THEN 'GPV'
  WHEN 54 THEN 'GOV'
  WHEN 55 THEN 'TT'
  WHEN 56 THEN 'TSG'
  WHEN 57 THEN 'TKP'
  WHEN 58 THEN 'TSČ'
  WHEN 59 THEN 'TZ'
  WHEN 64 THEN 'OPA'
  WHEN 65 THEN 'OIS'
  WHEN 66 THEN 'PKP'
  WHEN 67 THEN 'ZNŽ'
  ELSE UPPER(LEFT(name, 4))
END
WHERE "abbrevation" = '';

ALTER TABLE "Subject"
  ALTER COLUMN "abbrevation" DROP DEFAULT;

UPDATE "Teacher"
SET "color" = NULL
WHERE "color" = '#000000';

ALTER TABLE "Teacher"
  ALTER COLUMN "color" DROP DEFAULT;

ALTER TABLE "Teacher"
  ALTER COLUMN "color" DROP NOT NULL;
